NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authors.urls')),
    path('sign/', include('sign.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
]

authors/urls.py
from django.urls import path
from .views import *
app_name = "authors"

urlpatterns = [
   path('', home, name="home"),
   path('news', PostsList.as_view(), name="posts"),
   path('news/search/', PostsSearch.as_view(), name="search"),
   path('news/<int:pk>', PostDetail.as_view(), name="post"),

   path('news/create/', NewsCreate.as_view(),name='news-create'),
   path('article/create/', NewsCreate.as_view(),name='article-create'),

   path('news/edit/<int:pk>', PostFormView.as_view(), name='news-edit'),
   path('article/edit/<int:pk>', PostFormView.as_view(), name='article-edit'),

   path('news/delete/<int:pk>', PostDeleteView.as_view(), name='news-delete'),
   path('article/delete/<int:pk>', PostDeleteView.as_view(), name='article-delete'),

   path('subscribe', Subscribe.as_view(), name = 'subscribe')
]

sign/urls.py
from django.urls import path

from .views import upgrade_me
app_name = "sign"
urlpatterns = [
    path('upgrade/', upgrade_me, name = 'upgrade')
]

templates/edit_post.html
{% extends 'flatpages/default.html' %}

{%block content%}

  <form method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Send message">
  </form>

{%endblock content%}

templates/make_Subscribe.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscribe
{% endblock title %}

{% block content %}

<form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='submit'>
</form>

{% endblock content %}

templates/post.html
{% extends 'flatpages/default.html' %}
{% load censor %}


{% block title %}
Post {{post.title|my_censor}} - type {{ post.type }}
{% endblock title %}


{% block content %}
<h1>{{post.title|my_censor}}</h1><span>{{post.author.user.username}}</span>
<br> {{ post.text|my_censor }} <br> rating {{post.rating}} <br> {{post.created_at|date:'d M Y'}}<hr>
<hr>
<h2>категории:</h2>
{% for category in post.categories.all %}
<span>{{category.name}}</span>
{% endfor %}
{% endblock content %}

templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Author {{ user }} add new post {{title}}</h2>
    <p> {{text}} </p>
</body>
</html>

templates/posts.html
{% extends 'flatpages/default.html' %}
{% load censor %}
{% load censor custom_tags%}

{% block title %}
Posts
{% endblock title %}


{% block content %}
{% if is_not_authors %}
<button> <a href="{% url 'sign:upgrade'%}"> стать автором!</a> </button>
{% endif %}
<form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
<h1>Все статьи {{posts|length}}</h1>
{% for post in posts %}
<p><a href="{% url 'authors:post' pk=post.pk %}">{{ post.title|my_censor }}</a>
{% if post.type == 'A' %}
    <a href="{% url 'authors:article-edit' pk=post.pk %}">Edit</a>
    <a href="{% url 'authors:article-delete' pk=post.pk %}">Delete</a>
{% else %}
    <a href="{% url 'authors:news-edit' pk=post.pk %}">Edit</a>
    <a href="{% url 'authors:news-delete' pk=post.pk %}">Delete</a>
{% endif %}

    </p>
<br> {{post.created_at|date:'d M Y'}} <br> {{ post.text|truncatechars:20|my_censor }}

<hr>
{% endfor %}
{% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/search.html
{% extends 'flatpages/default.html' %}
{% load censor %}
{% load censor custom_tags%}

{% block title %}
Posts
{% endblock title %}


{% block content %}
<form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
<h1>Все статьи {{posts|length}}</h1>
{% for post in posts %}
<a href="{% url 'authors:post' pk=post.pk %}">{{ post.title|my_censor }}</a>
<br> {{post.created_at|date:'d M Y'}} <br> {{ post.text|truncatechars:20|my_censor }}<hr>
{% endfor %}
{% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}